Connect api
gids-dadi/the-bookstore-app pull request #4
Opened 2022-06-10 19:49 UTC by gids-dadi

The PR contains logic to connect to the bookstore API

2022-06-10 21:55 UTC, brytebee requested changes
Hi, @gids-dadi👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- `redux-thunk` is added to the project as a package and used as middleware.✔️
- All [Bookstore API](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) calls are done with [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).✔️
- Action Creator for fetching books should be created and returns a function.✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-10 21:55 UTC, brytebee commented on src/redux/books/books.js
> +      }),
- [ ] **Required:**  While you have done an awesome job here, the book object is never posted. This is because the `bookstore API` is expecting a certain `format` of data as its `request` but you are sending the wrong format. Consider this code block below to fix the format.
```
 body: JSON.stringify({
      item_id: payload.id,
      title: payload.title,
      author: payload.author,
      category: payload.category,
    }),

2022-06-10 21:55 UTC, brytebee commented on src/redux/books/books.js
> +  // console.log(books);
- [ ] **Required:** To maintain a professional README.md remove commented and unused code.

2022-06-10 21:55 UTC, brytebee commented on src/redux/books/books.js
> +export const getBook = async (dispatch) => {
- [ ] **Required:** Your get function uses the correct AJAX fetch method, however, the data is not gotten from the DB because 
- Although you have an async function to get data in your code, you have not called this function anywhere in your codebase.
- Call the code in the component you intend to display the gotten data.
- You need to call it inside a `useEffect()`. Consider this snippet 

```
useEffect(() => {
    dispatch(getBook());
  }, []);

2022-06-11 09:43 UTC, topeogunleye approved these changes
### Hi @gids-dadi, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
> * [ ]  Please check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-11 09:43 UTC, topeogunleye commented on src/redux/books/books.js
> +      //   bookTitle: payload.title,
- [ ] [OPTIONAL] I kindly suggest that you remove commented-out code from your codebase as it doesn't make your code neat.

2022-06-13 15:39 UTC, merged